Repository SebasRod23/queue-model-simulator, pull requests merged in 2021-11, with the labels that each got.

#2 Project structure & Dependencies
  .gitignore
  README.md
  package.json
  public/index.html
  src/App.tsx
  src/index.tsx
  src/react-app-env.d.ts
  src/styles/index.css
  src/styles/styles.ts
  tsconfig.json
  yarn.lock
Labels: enhancement

#4 Github Pages & Actions
  .github/workflows/build-deploy.yml
  package.json
  yarn.lock
Labels: enhancement

#12 Input fields with validation
  src/App.tsx
  src/components/InputQueueModel.tsx
  src/containers/Layout.tsx
  src/enums/QueueModelsOptions.ts
  src/interfaces/types.ts
Labels: enhancement

#13 Queue model data UI
  package.json
  src/components/InputQueueModel.tsx
  src/components/PnCalculator.tsx
  src/components/QueueModelCharacteristics.tsx
  src/containers/Layout.tsx
  src/interfaces/types.ts
  yarn.lock
Labels: enhancement

#9 Queue basic classes
  src/classes/MM1.ts
  src/classes/MMs.ts
  src/classes/MMsk.ts
  src/containers/test.tsx
  src/interfaces/QueueData.ts
  yarn.lock
Labels: enhancement

#17 Calculate cost function
  src/classes/MEk1.ts
  src/classes/MG1.ts
  src/classes/MM1.ts
  src/classes/MMs.ts
  src/classes/MMsk.ts
Labels: enhancement

#19 Connect Queue models logic to UI
  src/classes/MEk1.ts
  src/classes/MG1.ts
  src/classes/MM1.ts
  src/classes/MMs.ts
  src/classes/MMsk.ts
  src/components/InputQueueModel.tsx
  src/components/PnCalculator.tsx
  src/components/QueueModelCharacteristics.tsx
  src/components/QueueModelCost.tsx
  src/containers/Layout.tsx
  src/enums/QueueModelsOptions.ts
  src/interfaces/QueueData.ts
  src/interfaces/types.ts
  src/utils/convertInputToValues.ts
Labels: enhancement

#20 Readme
  README.md
  src/components/QueueModelCost.tsx
Labels: documentation

#21 Improvements and fixes
  src/classes/MEk1.ts
  src/classes/MG1.ts
  src/classes/MM1.ts
  src/classes/MMs.ts
  src/classes/MMsk.ts
  src/components/InputQueueModel.tsx
  src/components/PnCalculator.tsx
  src/components/QueueModelCost.tsx
  src/components/WarningSnackbar.tsx
  src/containers/Layout.tsx
  src/containers/test.tsx
Labels: bug, enhancement

#22 Fix validation bugs
  src/classes/MMs.ts
  src/classes/MMsk.ts
Labels: bug
